package com.google.android.gms.internal.mlkit_vision_internal_vkp;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import com.undatech.opaque.input.RemoteKeyboard;
import java.io.IOException;
import org.apache.commons.compress.archivers.tar.TarConstants;

/* JADX INFO: compiled from: com.google.mlkit:vision-internal-vkp@@18.2.3 */
/* JADX INFO: loaded from: classes.dex */
final class zzama implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zzama zza = new zzama();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaZ;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzba;
    private static final FieldDescriptor zzbb;
    private static final FieldDescriptor zzbc;
    private static final FieldDescriptor zzbd;
    private static final FieldDescriptor zzbe;
    private static final FieldDescriptor zzbf;
    private static final FieldDescriptor zzbg;
    private static final FieldDescriptor zzbh;
    private static final FieldDescriptor zzbi;
    private static final FieldDescriptor zzbj;
    private static final FieldDescriptor zzbk;
    private static final FieldDescriptor zzbl;
    private static final FieldDescriptor zzbm;
    private static final FieldDescriptor zzbn;
    private static final FieldDescriptor zzbo;
    private static final FieldDescriptor zzbp;
    private static final FieldDescriptor zzbq;
    private static final FieldDescriptor zzbr;
    private static final FieldDescriptor zzbs;
    private static final FieldDescriptor zzbt;
    private static final FieldDescriptor zzbu;
    private static final FieldDescriptor zzbv;
    private static final FieldDescriptor zzbw;
    private static final FieldDescriptor zzbx;
    private static final FieldDescriptor zzby;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zznn zznnVar = new zznn();
        zznnVar.zza(1);
        zzb = builder.withProperty(zznnVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zznn zznnVar2 = new zznn();
        zznnVar2.zza(2);
        zzc = builder2.withProperty(zznnVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zznn zznnVar3 = new zznn();
        zznnVar3.zza(37);
        zzd = builder3.withProperty(zznnVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zznn zznnVar4 = new zznn();
        zznnVar4.zza(61);
        zze = builder4.withProperty(zznnVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zznn zznnVar5 = new zznn();
        zznnVar5.zza(3);
        zzf = builder5.withProperty(zznnVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zznn zznnVar6 = new zznn();
        zznnVar6.zza(20);
        zzg = builder6.withProperty(zznnVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zznn zznnVar7 = new zznn();
        zznnVar7.zza(4);
        zzh = builder7.withProperty(zznnVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zznn zznnVar8 = new zznn();
        zznnVar8.zza(29);
        zzi = builder8.withProperty(zznnVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zznn zznnVar9 = new zznn();
        zznnVar9.zza(5);
        zzj = builder9.withProperty(zznnVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zznn zznnVar10 = new zznn();
        zznnVar10.zza(59);
        zzk = builder10.withProperty(zznnVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zznn zznnVar11 = new zznn();
        zznnVar11.zza(6);
        zzl = builder11.withProperty(zznnVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zznn zznnVar12 = new zznn();
        zznnVar12.zza(79);
        zzm = builder12.withProperty(zznnVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zznn zznnVar13 = new zznn();
        zznnVar13.zza(7);
        zzn = builder13.withProperty(zznnVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zznn zznnVar14 = new zznn();
        zznnVar14.zza(58);
        zzo = builder14.withProperty(zznnVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zznn zznnVar15 = new zznn();
        zznnVar15.zza(48);
        zzp = builder15.withProperty(zznnVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zznn zznnVar16 = new zznn();
        zznnVar16.zza(49);
        zzq = builder16.withProperty(zznnVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zznn zznnVar17 = new zznn();
        zznnVar17.zza(18);
        zzr = builder17.withProperty(zznnVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zznn zznnVar18 = new zznn();
        zznnVar18.zza(26);
        zzs = builder18.withProperty(zznnVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zznn zznnVar19 = new zznn();
        zznnVar19.zza(27);
        zzt = builder19.withProperty(zznnVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zznn zznnVar20 = new zznn();
        zznnVar20.zza(28);
        zzu = builder20.withProperty(zznnVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zznn zznnVar21 = new zznn();
        zznnVar21.zza(44);
        zzv = builder21.withProperty(zznnVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zznn zznnVar22 = new zznn();
        zznnVar22.zza(45);
        zzw = builder22.withProperty(zznnVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zznn zznnVar23 = new zznn();
        zznnVar23.zza(19);
        zzx = builder23.withProperty(zznnVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zznn zznnVar24 = new zznn();
        zznnVar24.zza(21);
        zzy = builder24.withProperty(zznnVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zznn zznnVar25 = new zznn();
        zznnVar25.zza(22);
        zzz = builder25.withProperty(zznnVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zznn zznnVar26 = new zznn();
        zznnVar26.zza(8);
        zzA = builder26.withProperty(zznnVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zznn zznnVar27 = new zznn();
        zznnVar27.zza(9);
        zzB = builder27.withProperty(zznnVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zznn zznnVar28 = new zznn();
        zznnVar28.zza(10);
        zzC = builder28.withProperty(zznnVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zznn zznnVar29 = new zznn();
        zznnVar29.zza(11);
        zzD = builder29.withProperty(zznnVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zznn zznnVar30 = new zznn();
        zznnVar30.zza(12);
        zzE = builder30.withProperty(zznnVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zznn zznnVar31 = new zznn();
        zznnVar31.zza(13);
        zzF = builder31.withProperty(zznnVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zznn zznnVar32 = new zznn();
        zznnVar32.zza(14);
        zzG = builder32.withProperty(zznnVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zznn zznnVar33 = new zznn();
        zznnVar33.zza(15);
        zzH = builder33.withProperty(zznnVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zznn zznnVar34 = new zznn();
        zznnVar34.zza(16);
        zzI = builder34.withProperty(zznnVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zznn zznnVar35 = new zznn();
        zznnVar35.zza(17);
        zzJ = builder35.withProperty(zznnVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zznn zznnVar36 = new zznn();
        zznnVar36.zza(23);
        zzK = builder36.withProperty(zznnVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zznn zznnVar37 = new zznn();
        zznnVar37.zza(24);
        zzL = builder37.withProperty(zznnVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zznn zznnVar38 = new zznn();
        zznnVar38.zza(25);
        zzM = builder38.withProperty(zznnVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zznn zznnVar39 = new zznn();
        zznnVar39.zza(39);
        zzN = builder39.withProperty(zznnVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zznn zznnVar40 = new zznn();
        zznnVar40.zza(40);
        zzO = builder40.withProperty(zznnVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zznn zznnVar41 = new zznn();
        zznnVar41.zza(30);
        zzP = builder41.withProperty(zznnVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zznn zznnVar42 = new zznn();
        zznnVar42.zza(31);
        zzQ = builder42.withProperty(zznnVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zznn zznnVar43 = new zznn();
        zznnVar43.zza(32);
        zzR = builder43.withProperty(zznnVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zznn zznnVar44 = new zznn();
        zznnVar44.zza(33);
        zzS = builder44.withProperty(zznnVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zznn zznnVar45 = new zznn();
        zznnVar45.zza(34);
        zzT = builder45.withProperty(zznnVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zznn zznnVar46 = new zznn();
        zznnVar46.zza(35);
        zzU = builder46.withProperty(zznnVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zznn zznnVar47 = new zznn();
        zznnVar47.zza(36);
        zzV = builder47.withProperty(zznnVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zznn zznnVar48 = new zznn();
        zznnVar48.zza(46);
        zzW = builder48.withProperty(zznnVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zznn zznnVar49 = new zznn();
        zznnVar49.zza(47);
        zzX = builder49.withProperty(zznnVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zznn zznnVar50 = new zznn();
        zznnVar50.zza(69);
        zzY = builder50.withProperty(zznnVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zznn zznnVar51 = new zznn();
        zznnVar51.zza(42);
        zzZ = builder51.withProperty(zznnVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zznn zznnVar52 = new zznn();
        zznnVar52.zza(50);
        zzaa = builder52.withProperty(zznnVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zznn zznnVar53 = new zznn();
        zznnVar53.zza(51);
        zzab = builder53.withProperty(zznnVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zznn zznnVar54 = new zznn();
        zznnVar54.zza(52);
        zzac = builder54.withProperty(zznnVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zznn zznnVar55 = new zznn();
        zznnVar55.zza(53);
        zzad = builder55.withProperty(zznnVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zznn zznnVar56 = new zznn();
        zznnVar56.zza(54);
        zzae = builder56.withProperty(zznnVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zznn zznnVar57 = new zznn();
        zznnVar57.zza(60);
        zzaf = builder57.withProperty(zznnVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zznn zznnVar58 = new zznn();
        zznnVar58.zza(85);
        zzag = builder58.withProperty(zznnVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zznn zznnVar59 = new zznn();
        zznnVar59.zza(86);
        zzah = builder59.withProperty(zznnVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zznn zznnVar60 = new zznn();
        zznnVar60.zza(87);
        zzai = builder60.withProperty(zznnVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zznn zznnVar61 = new zznn();
        zznnVar61.zza(55);
        zzaj = builder61.withProperty(zznnVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zznn zznnVar62 = new zznn();
        zznnVar62.zza(56);
        zzak = builder62.withProperty(zznnVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zznn zznnVar63 = new zznn();
        zznnVar63.zza(57);
        zzal = builder63.withProperty(zznnVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zznn zznnVar64 = new zznn();
        zznnVar64.zza(62);
        zzam = builder64.withProperty(zznnVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zznn zznnVar65 = new zznn();
        zznnVar65.zza(63);
        zzan = builder65.withProperty(zznnVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zznn zznnVar66 = new zznn();
        zznnVar66.zza(64);
        zzao = builder66.withProperty(zznnVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zznn zznnVar67 = new zznn();
        zznnVar67.zza(65);
        zzap = builder67.withProperty(zznnVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zznn zznnVar68 = new zznn();
        zznnVar68.zza(66);
        zzaq = builder68.withProperty(zznnVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zznn zznnVar69 = new zznn();
        zznnVar69.zza(67);
        zzar = builder69.withProperty(zznnVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zznn zznnVar70 = new zznn();
        zznnVar70.zza(68);
        zzas = builder70.withProperty(zznnVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zznn zznnVar71 = new zznn();
        zznnVar71.zza(70);
        zzat = builder71.withProperty(zznnVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zznn zznnVar72 = new zznn();
        zznnVar72.zza(71);
        zzau = builder72.withProperty(zznnVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zznn zznnVar73 = new zznn();
        zznnVar73.zza(72);
        zzav = builder73.withProperty(zznnVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zznn zznnVar74 = new zznn();
        zznnVar74.zza(73);
        zzaw = builder74.withProperty(zznnVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zznn zznnVar75 = new zznn();
        zznnVar75.zza(74);
        zzax = builder75.withProperty(zznnVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zznn zznnVar76 = new zznn();
        zznnVar76.zza(75);
        zzay = builder76.withProperty(zznnVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zznn zznnVar77 = new zznn();
        zznnVar77.zza(76);
        zzaz = builder77.withProperty(zznnVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zznn zznnVar78 = new zznn();
        zznnVar78.zza(77);
        zzaA = builder78.withProperty(zznnVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zznn zznnVar79 = new zznn();
        zznnVar79.zza(78);
        zzaB = builder79.withProperty(zznnVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zznn zznnVar80 = new zznn();
        zznnVar80.zza(80);
        zzaC = builder80.withProperty(zznnVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zznn zznnVar81 = new zznn();
        zznnVar81.zza(81);
        zzaD = builder81.withProperty(zznnVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zznn zznnVar82 = new zznn();
        zznnVar82.zza(82);
        zzaE = builder82.withProperty(zznnVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zznn zznnVar83 = new zznn();
        zznnVar83.zza(83);
        zzaF = builder83.withProperty(zznnVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zznn zznnVar84 = new zznn();
        zznnVar84.zza(84);
        zzaG = builder84.withProperty(zznnVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zznn zznnVar85 = new zznn();
        zznnVar85.zza(88);
        zzaH = builder85.withProperty(zznnVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zznn zznnVar86 = new zznn();
        zznnVar86.zza(89);
        zzaI = builder86.withProperty(zznnVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zznn zznnVar87 = new zznn();
        zznnVar87.zza(90);
        zzaJ = builder87.withProperty(zznnVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zznn zznnVar88 = new zznn();
        zznnVar88.zza(91);
        zzaK = builder88.withProperty(zznnVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zznn zznnVar89 = new zznn();
        zznnVar89.zza(92);
        zzaL = builder89.withProperty(zznnVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zznn zznnVar90 = new zznn();
        zznnVar90.zza(93);
        zzaM = builder90.withProperty(zznnVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zznn zznnVar91 = new zznn();
        zznnVar91.zza(94);
        zzaN = builder91.withProperty(zznnVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zznn zznnVar92 = new zznn();
        zznnVar92.zza(95);
        zzaO = builder92.withProperty(zznnVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zznn zznnVar93 = new zznn();
        zznnVar93.zza(96);
        zzaP = builder93.withProperty(zznnVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zznn zznnVar94 = new zznn();
        zznnVar94.zza(97);
        zzaQ = builder94.withProperty(zznnVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zznn zznnVar95 = new zznn();
        zznnVar95.zza(98);
        zzaR = builder95.withProperty(zznnVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zznn zznnVar96 = new zznn();
        zznnVar96.zza(99);
        zzaS = builder96.withProperty(zznnVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zznn zznnVar97 = new zznn();
        zznnVar97.zza(100);
        zzaT = builder97.withProperty(zznnVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zznn zznnVar98 = new zznn();
        zznnVar98.zza(101);
        zzaU = builder98.withProperty(zznnVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zznn zznnVar99 = new zznn();
        zznnVar99.zza(102);
        zzaV = builder99.withProperty(zznnVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zznn zznnVar100 = new zznn();
        zznnVar100.zza(103);
        zzaW = builder100.withProperty(zznnVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zznn zznnVar101 = new zznn();
        zznnVar101.zza(104);
        zzaX = builder101.withProperty(zznnVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zznn zznnVar102 = new zznn();
        zznnVar102.zza(105);
        zzaY = builder102.withProperty(zznnVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zznn zznnVar103 = new zznn();
        zznnVar103.zza(106);
        zzaZ = builder103.withProperty(zznnVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zznn zznnVar104 = new zznn();
        zznnVar104.zza(107);
        zzba = builder104.withProperty(zznnVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zznn zznnVar105 = new zznn();
        zznnVar105.zza(108);
        zzbb = builder105.withProperty(zznnVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zznn zznnVar106 = new zznn();
        zznnVar106.zza(109);
        zzbc = builder106.withProperty(zznnVar106.zzb()).build();
        FieldDescriptor.Builder builder107 = FieldDescriptor.builder("onDeviceStainRemovalLogEvent");
        zznn zznnVar107 = new zznn();
        zznnVar107.zza(110);
        zzbd = builder107.withProperty(zznnVar107.zzb()).build();
        FieldDescriptor.Builder builder108 = FieldDescriptor.builder("aggregatedOnDeviceStainRemovalLogEvent");
        zznn zznnVar108 = new zznn();
        zznnVar108.zza(RemoteKeyboard.SCAN_DELETE);
        zzbe = builder108.withProperty(zznnVar108.zzb()).build();
        FieldDescriptor.Builder builder109 = FieldDescriptor.builder("stainRemovalOptionalModuleLogEvent");
        zznn zznnVar109 = new zznn();
        zznnVar109.zza(112);
        zzbf = builder109.withProperty(zznnVar109.zzb()).build();
        FieldDescriptor.Builder builder110 = FieldDescriptor.builder("onDeviceShadowRemovalLogEvent");
        zznn zznnVar110 = new zznn();
        zznnVar110.zza(113);
        zzbg = builder110.withProperty(zznnVar110.zzb()).build();
        FieldDescriptor.Builder builder111 = FieldDescriptor.builder("aggregatedOnDeviceShadowRemovalLogEvent");
        zznn zznnVar111 = new zznn();
        zznnVar111.zza(114);
        zzbh = builder111.withProperty(zznnVar111.zzb()).build();
        FieldDescriptor.Builder builder112 = FieldDescriptor.builder("shadowRemovalOptionalModuleLogEvent");
        zznn zznnVar112 = new zznn();
        zznnVar112.zza(115);
        zzbi = builder112.withProperty(zznnVar112.zzb()).build();
        FieldDescriptor.Builder builder113 = FieldDescriptor.builder("onDeviceDigitalInkSegmentationLogEvent");
        zznn zznnVar113 = new zznn();
        zznnVar113.zza(116);
        zzbj = builder113.withProperty(zznnVar113.zzb()).build();
        FieldDescriptor.Builder builder114 = FieldDescriptor.builder("onDeviceDocumentScannerStartLogEvent");
        zznn zznnVar114 = new zznn();
        zznnVar114.zza(117);
        zzbk = builder114.withProperty(zznnVar114.zzb()).build();
        FieldDescriptor.Builder builder115 = FieldDescriptor.builder("onDeviceDocumentScannerFinishLogEvent");
        zznn zznnVar115 = new zznn();
        zznnVar115.zza(118);
        zzbl = builder115.withProperty(zznnVar115.zzb()).build();
        FieldDescriptor.Builder builder116 = FieldDescriptor.builder("onDeviceDocumentScannerUiStartLogEvent");
        zznn zznnVar116 = new zznn();
        zznnVar116.zza(119);
        zzbm = builder116.withProperty(zznnVar116.zzb()).build();
        FieldDescriptor.Builder builder117 = FieldDescriptor.builder("onDeviceDocumentScannerUiFinishLogEvent");
        zznn zznnVar117 = new zznn();
        zznnVar117.zza(120);
        zzbn = builder117.withProperty(zznnVar117.zzb()).build();
        FieldDescriptor.Builder builder118 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionStartLogEvent");
        zznn zznnVar118 = new zznn();
        zznnVar118.zza(121);
        zzbo = builder118.withProperty(zznnVar118.zzb()).build();
        FieldDescriptor.Builder builder119 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zznn zznnVar119 = new zznn();
        zznnVar119.zza(122);
        zzbp = builder119.withProperty(zznnVar119.zzb()).build();
        FieldDescriptor.Builder builder120 = FieldDescriptor.builder("onDeviceDocumentScannerUiCreateLogEvent");
        zznn zznnVar120 = new zznn();
        zznnVar120.zza(123);
        zzbq = builder120.withProperty(zznnVar120.zzb()).build();
        FieldDescriptor.Builder builder121 = FieldDescriptor.builder("onDeviceSubjectSegmentationCreateLogEvent");
        zznn zznnVar121 = new zznn();
        zznnVar121.zza(124);
        zzbr = builder121.withProperty(zznnVar121.zzb()).build();
        FieldDescriptor.Builder builder122 = FieldDescriptor.builder("onDeviceSubjectSegmentationLoadLogEvent");
        zznn zznnVar122 = new zznn();
        zznnVar122.zza(RemoteKeyboard.SCAN_LEFTSUPER);
        zzbs = builder122.withProperty(zznnVar122.zzb()).build();
        FieldDescriptor.Builder builder123 = FieldDescriptor.builder("onDeviceSubjectSegmentationInferenceLogEvent");
        zznn zznnVar123 = new zznn();
        zznnVar123.zza(126);
        zzbt = builder123.withProperty(zznnVar123.zzb()).build();
        FieldDescriptor.Builder builder124 = FieldDescriptor.builder("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zznn zznnVar124 = new zznn();
        zznnVar124.zza(127);
        zzbu = builder124.withProperty(zznnVar124.zzb()).build();
        FieldDescriptor.Builder builder125 = FieldDescriptor.builder("subjectSegmentationOptionalModuleLogEvent");
        zznn zznnVar125 = new zznn();
        zznnVar125.zza(128);
        zzbv = builder125.withProperty(zznnVar125.zzb()).build();
        FieldDescriptor.Builder builder126 = FieldDescriptor.builder("documentScannerUiModuleScreenViewEvent");
        zznn zznnVar126 = new zznn();
        zznnVar126.zza(129);
        zzbw = builder126.withProperty(zznnVar126.zzb()).build();
        FieldDescriptor.Builder builder127 = FieldDescriptor.builder("documentScannerUiModuleScreenClickEvent");
        zznn zznnVar127 = new zznn();
        zznnVar127.zza(130);
        zzbx = builder127.withProperty(zznnVar127.zzb()).build();
        FieldDescriptor.Builder builder128 = FieldDescriptor.builder("documentScannerUiModuleScreenErrorEvent");
        zznn zznnVar128 = new zznn();
        zznnVar128.zza(TarConstants.PREFIXLEN_XSTAR);
        zzby = builder128.withProperty(zznnVar128.zzb()).build();
    }

    private zzama() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzasb zzasbVar = (zzasb) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzasbVar.zzd());
        objectEncoderContext2.add(zzc, zzasbVar.zzb());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, (Object) null);
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, (Object) null);
        objectEncoderContext2.add(zzt, (Object) null);
        objectEncoderContext2.add(zzu, (Object) null);
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, (Object) null);
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, zzasbVar.zzc());
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, zzasbVar.zza());
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
        objectEncoderContext2.add(zzba, (Object) null);
        objectEncoderContext2.add(zzbb, (Object) null);
        objectEncoderContext2.add(zzbc, (Object) null);
        objectEncoderContext2.add(zzbd, (Object) null);
        objectEncoderContext2.add(zzbe, (Object) null);
        objectEncoderContext2.add(zzbf, (Object) null);
        objectEncoderContext2.add(zzbg, (Object) null);
        objectEncoderContext2.add(zzbh, (Object) null);
        objectEncoderContext2.add(zzbi, (Object) null);
        objectEncoderContext2.add(zzbj, (Object) null);
        objectEncoderContext2.add(zzbk, (Object) null);
        objectEncoderContext2.add(zzbl, (Object) null);
        objectEncoderContext2.add(zzbm, (Object) null);
        objectEncoderContext2.add(zzbn, (Object) null);
        objectEncoderContext2.add(zzbo, (Object) null);
        objectEncoderContext2.add(zzbp, (Object) null);
        objectEncoderContext2.add(zzbq, (Object) null);
        objectEncoderContext2.add(zzbr, (Object) null);
        objectEncoderContext2.add(zzbs, (Object) null);
        objectEncoderContext2.add(zzbt, (Object) null);
        objectEncoderContext2.add(zzbu, (Object) null);
        objectEncoderContext2.add(zzbv, (Object) null);
        objectEncoderContext2.add(zzbw, (Object) null);
        objectEncoderContext2.add(zzbx, (Object) null);
        objectEncoderContext2.add(zzby, (Object) null);
    }
}
