package com.google.android.gms.internal.mlkit_vision_object_detection_bundled;

import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import com.undatech.opaque.input.RemoteKeyboard;
import java.io.IOException;
import org.apache.commons.compress.archivers.tar.TarConstants;

/* JADX INFO: compiled from: com.google.mlkit:object-detection@@17.0.2 */
/* JADX INFO: loaded from: classes.dex */
final class zziu implements ObjectEncoder {
    private static final FieldDescriptor zzA;
    private static final FieldDescriptor zzB;
    private static final FieldDescriptor zzC;
    private static final FieldDescriptor zzD;
    private static final FieldDescriptor zzE;
    private static final FieldDescriptor zzF;
    private static final FieldDescriptor zzG;
    private static final FieldDescriptor zzH;
    private static final FieldDescriptor zzI;
    private static final FieldDescriptor zzJ;
    private static final FieldDescriptor zzK;
    private static final FieldDescriptor zzL;
    private static final FieldDescriptor zzM;
    private static final FieldDescriptor zzN;
    private static final FieldDescriptor zzO;
    private static final FieldDescriptor zzP;
    private static final FieldDescriptor zzQ;
    private static final FieldDescriptor zzR;
    private static final FieldDescriptor zzS;
    private static final FieldDescriptor zzT;
    private static final FieldDescriptor zzU;
    private static final FieldDescriptor zzV;
    private static final FieldDescriptor zzW;
    private static final FieldDescriptor zzX;
    private static final FieldDescriptor zzY;
    private static final FieldDescriptor zzZ;
    static final zziu zza = new zziu();
    private static final FieldDescriptor zzaA;
    private static final FieldDescriptor zzaB;
    private static final FieldDescriptor zzaC;
    private static final FieldDescriptor zzaD;
    private static final FieldDescriptor zzaE;
    private static final FieldDescriptor zzaF;
    private static final FieldDescriptor zzaG;
    private static final FieldDescriptor zzaH;
    private static final FieldDescriptor zzaI;
    private static final FieldDescriptor zzaJ;
    private static final FieldDescriptor zzaK;
    private static final FieldDescriptor zzaL;
    private static final FieldDescriptor zzaM;
    private static final FieldDescriptor zzaN;
    private static final FieldDescriptor zzaO;
    private static final FieldDescriptor zzaP;
    private static final FieldDescriptor zzaQ;
    private static final FieldDescriptor zzaR;
    private static final FieldDescriptor zzaS;
    private static final FieldDescriptor zzaT;
    private static final FieldDescriptor zzaU;
    private static final FieldDescriptor zzaV;
    private static final FieldDescriptor zzaW;
    private static final FieldDescriptor zzaX;
    private static final FieldDescriptor zzaY;
    private static final FieldDescriptor zzaZ;
    private static final FieldDescriptor zzaa;
    private static final FieldDescriptor zzab;
    private static final FieldDescriptor zzac;
    private static final FieldDescriptor zzad;
    private static final FieldDescriptor zzae;
    private static final FieldDescriptor zzaf;
    private static final FieldDescriptor zzag;
    private static final FieldDescriptor zzah;
    private static final FieldDescriptor zzai;
    private static final FieldDescriptor zzaj;
    private static final FieldDescriptor zzak;
    private static final FieldDescriptor zzal;
    private static final FieldDescriptor zzam;
    private static final FieldDescriptor zzan;
    private static final FieldDescriptor zzao;
    private static final FieldDescriptor zzap;
    private static final FieldDescriptor zzaq;
    private static final FieldDescriptor zzar;
    private static final FieldDescriptor zzas;
    private static final FieldDescriptor zzat;
    private static final FieldDescriptor zzau;
    private static final FieldDescriptor zzav;
    private static final FieldDescriptor zzaw;
    private static final FieldDescriptor zzax;
    private static final FieldDescriptor zzay;
    private static final FieldDescriptor zzaz;
    private static final FieldDescriptor zzb;
    private static final FieldDescriptor zzba;
    private static final FieldDescriptor zzbb;
    private static final FieldDescriptor zzbc;
    private static final FieldDescriptor zzbd;
    private static final FieldDescriptor zzbe;
    private static final FieldDescriptor zzbf;
    private static final FieldDescriptor zzbg;
    private static final FieldDescriptor zzbh;
    private static final FieldDescriptor zzbi;
    private static final FieldDescriptor zzbj;
    private static final FieldDescriptor zzbk;
    private static final FieldDescriptor zzbl;
    private static final FieldDescriptor zzbm;
    private static final FieldDescriptor zzbn;
    private static final FieldDescriptor zzbo;
    private static final FieldDescriptor zzbp;
    private static final FieldDescriptor zzbq;
    private static final FieldDescriptor zzbr;
    private static final FieldDescriptor zzbs;
    private static final FieldDescriptor zzbt;
    private static final FieldDescriptor zzbu;
    private static final FieldDescriptor zzbv;
    private static final FieldDescriptor zzbw;
    private static final FieldDescriptor zzbx;
    private static final FieldDescriptor zzby;
    private static final FieldDescriptor zzc;
    private static final FieldDescriptor zzd;
    private static final FieldDescriptor zze;
    private static final FieldDescriptor zzf;
    private static final FieldDescriptor zzg;
    private static final FieldDescriptor zzh;
    private static final FieldDescriptor zzi;
    private static final FieldDescriptor zzj;
    private static final FieldDescriptor zzk;
    private static final FieldDescriptor zzl;
    private static final FieldDescriptor zzm;
    private static final FieldDescriptor zzn;
    private static final FieldDescriptor zzo;
    private static final FieldDescriptor zzp;
    private static final FieldDescriptor zzq;
    private static final FieldDescriptor zzr;
    private static final FieldDescriptor zzs;
    private static final FieldDescriptor zzt;
    private static final FieldDescriptor zzu;
    private static final FieldDescriptor zzv;
    private static final FieldDescriptor zzw;
    private static final FieldDescriptor zzx;
    private static final FieldDescriptor zzy;
    private static final FieldDescriptor zzz;

    static {
        FieldDescriptor.Builder builder = FieldDescriptor.builder("systemInfo");
        zzbu zzbuVar = new zzbu();
        zzbuVar.zza(1);
        zzb = builder.withProperty(zzbuVar.zzb()).build();
        FieldDescriptor.Builder builder2 = FieldDescriptor.builder("eventName");
        zzbu zzbuVar2 = new zzbu();
        zzbuVar2.zza(2);
        zzc = builder2.withProperty(zzbuVar2.zzb()).build();
        FieldDescriptor.Builder builder3 = FieldDescriptor.builder("isThickClient");
        zzbu zzbuVar3 = new zzbu();
        zzbuVar3.zza(37);
        zzd = builder3.withProperty(zzbuVar3.zzb()).build();
        FieldDescriptor.Builder builder4 = FieldDescriptor.builder("clientType");
        zzbu zzbuVar4 = new zzbu();
        zzbuVar4.zza(61);
        zze = builder4.withProperty(zzbuVar4.zzb()).build();
        FieldDescriptor.Builder builder5 = FieldDescriptor.builder("modelDownloadLogEvent");
        zzbu zzbuVar5 = new zzbu();
        zzbuVar5.zza(3);
        zzf = builder5.withProperty(zzbuVar5.zzb()).build();
        FieldDescriptor.Builder builder6 = FieldDescriptor.builder("customModelLoadLogEvent");
        zzbu zzbuVar6 = new zzbu();
        zzbuVar6.zza(20);
        zzg = builder6.withProperty(zzbuVar6.zzb()).build();
        FieldDescriptor.Builder builder7 = FieldDescriptor.builder("customModelInferenceLogEvent");
        zzbu zzbuVar7 = new zzbu();
        zzbuVar7.zza(4);
        zzh = builder7.withProperty(zzbuVar7.zzb()).build();
        FieldDescriptor.Builder builder8 = FieldDescriptor.builder("customModelCreateLogEvent");
        zzbu zzbuVar8 = new zzbu();
        zzbuVar8.zza(29);
        zzi = builder8.withProperty(zzbuVar8.zzb()).build();
        FieldDescriptor.Builder builder9 = FieldDescriptor.builder("onDeviceFaceDetectionLogEvent");
        zzbu zzbuVar9 = new zzbu();
        zzbuVar9.zza(5);
        zzj = builder9.withProperty(zzbuVar9.zzb()).build();
        FieldDescriptor.Builder builder10 = FieldDescriptor.builder("onDeviceFaceLoadLogEvent");
        zzbu zzbuVar10 = new zzbu();
        zzbuVar10.zza(59);
        zzk = builder10.withProperty(zzbuVar10.zzb()).build();
        FieldDescriptor.Builder builder11 = FieldDescriptor.builder("onDeviceTextDetectionLogEvent");
        zzbu zzbuVar11 = new zzbu();
        zzbuVar11.zza(6);
        zzl = builder11.withProperty(zzbuVar11.zzb()).build();
        FieldDescriptor.Builder builder12 = FieldDescriptor.builder("onDeviceTextDetectionLoadLogEvent");
        zzbu zzbuVar12 = new zzbu();
        zzbuVar12.zza(79);
        zzm = builder12.withProperty(zzbuVar12.zzb()).build();
        FieldDescriptor.Builder builder13 = FieldDescriptor.builder("onDeviceBarcodeDetectionLogEvent");
        zzbu zzbuVar13 = new zzbu();
        zzbuVar13.zza(7);
        zzn = builder13.withProperty(zzbuVar13.zzb()).build();
        FieldDescriptor.Builder builder14 = FieldDescriptor.builder("onDeviceBarcodeLoadLogEvent");
        zzbu zzbuVar14 = new zzbu();
        zzbuVar14.zza(58);
        zzo = builder14.withProperty(zzbuVar14.zzb()).build();
        FieldDescriptor.Builder builder15 = FieldDescriptor.builder("onDeviceImageLabelCreateLogEvent");
        zzbu zzbuVar15 = new zzbu();
        zzbuVar15.zza(48);
        zzp = builder15.withProperty(zzbuVar15.zzb()).build();
        FieldDescriptor.Builder builder16 = FieldDescriptor.builder("onDeviceImageLabelLoadLogEvent");
        zzbu zzbuVar16 = new zzbu();
        zzbuVar16.zza(49);
        zzq = builder16.withProperty(zzbuVar16.zzb()).build();
        FieldDescriptor.Builder builder17 = FieldDescriptor.builder("onDeviceImageLabelDetectionLogEvent");
        zzbu zzbuVar17 = new zzbu();
        zzbuVar17.zza(18);
        zzr = builder17.withProperty(zzbuVar17.zzb()).build();
        FieldDescriptor.Builder builder18 = FieldDescriptor.builder("onDeviceObjectCreateLogEvent");
        zzbu zzbuVar18 = new zzbu();
        zzbuVar18.zza(26);
        zzs = builder18.withProperty(zzbuVar18.zzb()).build();
        FieldDescriptor.Builder builder19 = FieldDescriptor.builder("onDeviceObjectLoadLogEvent");
        zzbu zzbuVar19 = new zzbu();
        zzbuVar19.zza(27);
        zzt = builder19.withProperty(zzbuVar19.zzb()).build();
        FieldDescriptor.Builder builder20 = FieldDescriptor.builder("onDeviceObjectInferenceLogEvent");
        zzbu zzbuVar20 = new zzbu();
        zzbuVar20.zza(28);
        zzu = builder20.withProperty(zzbuVar20.zzb()).build();
        FieldDescriptor.Builder builder21 = FieldDescriptor.builder("onDevicePoseDetectionLogEvent");
        zzbu zzbuVar21 = new zzbu();
        zzbuVar21.zza(44);
        zzv = builder21.withProperty(zzbuVar21.zzb()).build();
        FieldDescriptor.Builder builder22 = FieldDescriptor.builder("onDeviceSegmentationLogEvent");
        zzbu zzbuVar22 = new zzbu();
        zzbuVar22.zza(45);
        zzw = builder22.withProperty(zzbuVar22.zzb()).build();
        FieldDescriptor.Builder builder23 = FieldDescriptor.builder("onDeviceSmartReplyLogEvent");
        zzbu zzbuVar23 = new zzbu();
        zzbuVar23.zza(19);
        zzx = builder23.withProperty(zzbuVar23.zzb()).build();
        FieldDescriptor.Builder builder24 = FieldDescriptor.builder("onDeviceLanguageIdentificationLogEvent");
        zzbu zzbuVar24 = new zzbu();
        zzbuVar24.zza(21);
        zzy = builder24.withProperty(zzbuVar24.zzb()).build();
        FieldDescriptor.Builder builder25 = FieldDescriptor.builder("onDeviceTranslationLogEvent");
        zzbu zzbuVar25 = new zzbu();
        zzbuVar25.zza(22);
        zzz = builder25.withProperty(zzbuVar25.zzb()).build();
        FieldDescriptor.Builder builder26 = FieldDescriptor.builder("cloudFaceDetectionLogEvent");
        zzbu zzbuVar26 = new zzbu();
        zzbuVar26.zza(8);
        zzA = builder26.withProperty(zzbuVar26.zzb()).build();
        FieldDescriptor.Builder builder27 = FieldDescriptor.builder("cloudCropHintDetectionLogEvent");
        zzbu zzbuVar27 = new zzbu();
        zzbuVar27.zza(9);
        zzB = builder27.withProperty(zzbuVar27.zzb()).build();
        FieldDescriptor.Builder builder28 = FieldDescriptor.builder("cloudDocumentTextDetectionLogEvent");
        zzbu zzbuVar28 = new zzbu();
        zzbuVar28.zza(10);
        zzC = builder28.withProperty(zzbuVar28.zzb()).build();
        FieldDescriptor.Builder builder29 = FieldDescriptor.builder("cloudImagePropertiesDetectionLogEvent");
        zzbu zzbuVar29 = new zzbu();
        zzbuVar29.zza(11);
        zzD = builder29.withProperty(zzbuVar29.zzb()).build();
        FieldDescriptor.Builder builder30 = FieldDescriptor.builder("cloudImageLabelDetectionLogEvent");
        zzbu zzbuVar30 = new zzbu();
        zzbuVar30.zza(12);
        zzE = builder30.withProperty(zzbuVar30.zzb()).build();
        FieldDescriptor.Builder builder31 = FieldDescriptor.builder("cloudLandmarkDetectionLogEvent");
        zzbu zzbuVar31 = new zzbu();
        zzbuVar31.zza(13);
        zzF = builder31.withProperty(zzbuVar31.zzb()).build();
        FieldDescriptor.Builder builder32 = FieldDescriptor.builder("cloudLogoDetectionLogEvent");
        zzbu zzbuVar32 = new zzbu();
        zzbuVar32.zza(14);
        zzG = builder32.withProperty(zzbuVar32.zzb()).build();
        FieldDescriptor.Builder builder33 = FieldDescriptor.builder("cloudSafeSearchDetectionLogEvent");
        zzbu zzbuVar33 = new zzbu();
        zzbuVar33.zza(15);
        zzH = builder33.withProperty(zzbuVar33.zzb()).build();
        FieldDescriptor.Builder builder34 = FieldDescriptor.builder("cloudTextDetectionLogEvent");
        zzbu zzbuVar34 = new zzbu();
        zzbuVar34.zza(16);
        zzI = builder34.withProperty(zzbuVar34.zzb()).build();
        FieldDescriptor.Builder builder35 = FieldDescriptor.builder("cloudWebSearchDetectionLogEvent");
        zzbu zzbuVar35 = new zzbu();
        zzbuVar35.zza(17);
        zzJ = builder35.withProperty(zzbuVar35.zzb()).build();
        FieldDescriptor.Builder builder36 = FieldDescriptor.builder("automlImageLabelingCreateLogEvent");
        zzbu zzbuVar36 = new zzbu();
        zzbuVar36.zza(23);
        zzK = builder36.withProperty(zzbuVar36.zzb()).build();
        FieldDescriptor.Builder builder37 = FieldDescriptor.builder("automlImageLabelingLoadLogEvent");
        zzbu zzbuVar37 = new zzbu();
        zzbuVar37.zza(24);
        zzL = builder37.withProperty(zzbuVar37.zzb()).build();
        FieldDescriptor.Builder builder38 = FieldDescriptor.builder("automlImageLabelingInferenceLogEvent");
        zzbu zzbuVar38 = new zzbu();
        zzbuVar38.zza(25);
        zzM = builder38.withProperty(zzbuVar38.zzb()).build();
        FieldDescriptor.Builder builder39 = FieldDescriptor.builder("isModelDownloadedLogEvent");
        zzbu zzbuVar39 = new zzbu();
        zzbuVar39.zza(39);
        zzN = builder39.withProperty(zzbuVar39.zzb()).build();
        FieldDescriptor.Builder builder40 = FieldDescriptor.builder("deleteModelLogEvent");
        zzbu zzbuVar40 = new zzbu();
        zzbuVar40.zza(40);
        zzO = builder40.withProperty(zzbuVar40.zzb()).build();
        FieldDescriptor.Builder builder41 = FieldDescriptor.builder("aggregatedAutomlImageLabelingInferenceLogEvent");
        zzbu zzbuVar41 = new zzbu();
        zzbuVar41.zza(30);
        zzP = builder41.withProperty(zzbuVar41.zzb()).build();
        FieldDescriptor.Builder builder42 = FieldDescriptor.builder("aggregatedCustomModelInferenceLogEvent");
        zzbu zzbuVar42 = new zzbu();
        zzbuVar42.zza(31);
        zzQ = builder42.withProperty(zzbuVar42.zzb()).build();
        FieldDescriptor.Builder builder43 = FieldDescriptor.builder("aggregatedOnDeviceFaceDetectionLogEvent");
        zzbu zzbuVar43 = new zzbu();
        zzbuVar43.zza(32);
        zzR = builder43.withProperty(zzbuVar43.zzb()).build();
        FieldDescriptor.Builder builder44 = FieldDescriptor.builder("aggregatedOnDeviceBarcodeDetectionLogEvent");
        zzbu zzbuVar44 = new zzbu();
        zzbuVar44.zza(33);
        zzS = builder44.withProperty(zzbuVar44.zzb()).build();
        FieldDescriptor.Builder builder45 = FieldDescriptor.builder("aggregatedOnDeviceImageLabelDetectionLogEvent");
        zzbu zzbuVar45 = new zzbu();
        zzbuVar45.zza(34);
        zzT = builder45.withProperty(zzbuVar45.zzb()).build();
        FieldDescriptor.Builder builder46 = FieldDescriptor.builder("aggregatedOnDeviceObjectInferenceLogEvent");
        zzbu zzbuVar46 = new zzbu();
        zzbuVar46.zza(35);
        zzU = builder46.withProperty(zzbuVar46.zzb()).build();
        FieldDescriptor.Builder builder47 = FieldDescriptor.builder("aggregatedOnDeviceTextDetectionLogEvent");
        zzbu zzbuVar47 = new zzbu();
        zzbuVar47.zza(36);
        zzV = builder47.withProperty(zzbuVar47.zzb()).build();
        FieldDescriptor.Builder builder48 = FieldDescriptor.builder("aggregatedOnDevicePoseDetectionLogEvent");
        zzbu zzbuVar48 = new zzbu();
        zzbuVar48.zza(46);
        zzW = builder48.withProperty(zzbuVar48.zzb()).build();
        FieldDescriptor.Builder builder49 = FieldDescriptor.builder("aggregatedOnDeviceSegmentationLogEvent");
        zzbu zzbuVar49 = new zzbu();
        zzbuVar49.zza(47);
        zzX = builder49.withProperty(zzbuVar49.zzb()).build();
        FieldDescriptor.Builder builder50 = FieldDescriptor.builder("pipelineAccelerationInferenceEvents");
        zzbu zzbuVar50 = new zzbu();
        zzbuVar50.zza(69);
        zzY = builder50.withProperty(zzbuVar50.zzb()).build();
        FieldDescriptor.Builder builder51 = FieldDescriptor.builder("remoteConfigLogEvent");
        zzbu zzbuVar51 = new zzbu();
        zzbuVar51.zza(42);
        zzZ = builder51.withProperty(zzbuVar51.zzb()).build();
        FieldDescriptor.Builder builder52 = FieldDescriptor.builder("inputImageConstructionLogEvent");
        zzbu zzbuVar52 = new zzbu();
        zzbuVar52.zza(50);
        zzaa = builder52.withProperty(zzbuVar52.zzb()).build();
        FieldDescriptor.Builder builder53 = FieldDescriptor.builder("leakedHandleEvent");
        zzbu zzbuVar53 = new zzbu();
        zzbuVar53.zza(51);
        zzab = builder53.withProperty(zzbuVar53.zzb()).build();
        FieldDescriptor.Builder builder54 = FieldDescriptor.builder("cameraSourceLogEvent");
        zzbu zzbuVar54 = new zzbu();
        zzbuVar54.zza(52);
        zzac = builder54.withProperty(zzbuVar54.zzb()).build();
        FieldDescriptor.Builder builder55 = FieldDescriptor.builder("imageLabelOptionalModuleLogEvent");
        zzbu zzbuVar55 = new zzbu();
        zzbuVar55.zza(53);
        zzad = builder55.withProperty(zzbuVar55.zzb()).build();
        FieldDescriptor.Builder builder56 = FieldDescriptor.builder("languageIdentificationOptionalModuleLogEvent");
        zzbu zzbuVar56 = new zzbu();
        zzbuVar56.zza(54);
        zzae = builder56.withProperty(zzbuVar56.zzb()).build();
        FieldDescriptor.Builder builder57 = FieldDescriptor.builder("faceDetectionOptionalModuleLogEvent");
        zzbu zzbuVar57 = new zzbu();
        zzbuVar57.zza(60);
        zzaf = builder57.withProperty(zzbuVar57.zzb()).build();
        FieldDescriptor.Builder builder58 = FieldDescriptor.builder("documentDetectionOptionalModuleLogEvent");
        zzbu zzbuVar58 = new zzbu();
        zzbuVar58.zza(85);
        zzag = builder58.withProperty(zzbuVar58.zzb()).build();
        FieldDescriptor.Builder builder59 = FieldDescriptor.builder("documentCroppingOptionalModuleLogEvent");
        zzbu zzbuVar59 = new zzbu();
        zzbuVar59.zza(86);
        zzah = builder59.withProperty(zzbuVar59.zzb()).build();
        FieldDescriptor.Builder builder60 = FieldDescriptor.builder("documentEnhancementOptionalModuleLogEvent");
        zzbu zzbuVar60 = new zzbu();
        zzbuVar60.zza(87);
        zzai = builder60.withProperty(zzbuVar60.zzb()).build();
        FieldDescriptor.Builder builder61 = FieldDescriptor.builder("nlClassifierOptionalModuleLogEvent");
        zzbu zzbuVar61 = new zzbu();
        zzbuVar61.zza(55);
        zzaj = builder61.withProperty(zzbuVar61.zzb()).build();
        FieldDescriptor.Builder builder62 = FieldDescriptor.builder("nlClassifierClientLibraryLogEvent");
        zzbu zzbuVar62 = new zzbu();
        zzbuVar62.zza(56);
        zzak = builder62.withProperty(zzbuVar62.zzb()).build();
        FieldDescriptor.Builder builder63 = FieldDescriptor.builder("accelerationAllowlistLogEvent");
        zzbu zzbuVar63 = new zzbu();
        zzbuVar63.zza(57);
        zzal = builder63.withProperty(zzbuVar63.zzb()).build();
        FieldDescriptor.Builder builder64 = FieldDescriptor.builder("toxicityDetectionCreateEvent");
        zzbu zzbuVar64 = new zzbu();
        zzbuVar64.zza(62);
        zzam = builder64.withProperty(zzbuVar64.zzb()).build();
        FieldDescriptor.Builder builder65 = FieldDescriptor.builder("toxicityDetectionLoadEvent");
        zzbu zzbuVar65 = new zzbu();
        zzbuVar65.zza(63);
        zzan = builder65.withProperty(zzbuVar65.zzb()).build();
        FieldDescriptor.Builder builder66 = FieldDescriptor.builder("toxicityDetectionInferenceEvent");
        zzbu zzbuVar66 = new zzbu();
        zzbuVar66.zza(64);
        zzao = builder66.withProperty(zzbuVar66.zzb()).build();
        FieldDescriptor.Builder builder67 = FieldDescriptor.builder("barcodeDetectionOptionalModuleLogEvent");
        zzbu zzbuVar67 = new zzbu();
        zzbuVar67.zza(65);
        zzap = builder67.withProperty(zzbuVar67.zzb()).build();
        FieldDescriptor.Builder builder68 = FieldDescriptor.builder("customImageLabelOptionalModuleLogEvent");
        zzbu zzbuVar68 = new zzbu();
        zzbuVar68.zza(66);
        zzaq = builder68.withProperty(zzbuVar68.zzb()).build();
        FieldDescriptor.Builder builder69 = FieldDescriptor.builder("codeScannerScanApiEvent");
        zzbu zzbuVar69 = new zzbu();
        zzbuVar69.zza(67);
        zzar = builder69.withProperty(zzbuVar69.zzb()).build();
        FieldDescriptor.Builder builder70 = FieldDescriptor.builder("codeScannerOptionalModuleEvent");
        zzbu zzbuVar70 = new zzbu();
        zzbuVar70.zza(68);
        zzas = builder70.withProperty(zzbuVar70.zzb()).build();
        FieldDescriptor.Builder builder71 = FieldDescriptor.builder("onDeviceExplicitContentCreateLogEvent");
        zzbu zzbuVar71 = new zzbu();
        zzbuVar71.zza(70);
        zzat = builder71.withProperty(zzbuVar71.zzb()).build();
        FieldDescriptor.Builder builder72 = FieldDescriptor.builder("onDeviceExplicitContentLoadLogEvent");
        zzbu zzbuVar72 = new zzbu();
        zzbuVar72.zza(71);
        zzau = builder72.withProperty(zzbuVar72.zzb()).build();
        FieldDescriptor.Builder builder73 = FieldDescriptor.builder("onDeviceExplicitContentInferenceLogEvent");
        zzbu zzbuVar73 = new zzbu();
        zzbuVar73.zza(72);
        zzav = builder73.withProperty(zzbuVar73.zzb()).build();
        FieldDescriptor.Builder builder74 = FieldDescriptor.builder("aggregatedOnDeviceExplicitContentLogEvent");
        zzbu zzbuVar74 = new zzbu();
        zzbuVar74.zza(73);
        zzaw = builder74.withProperty(zzbuVar74.zzb()).build();
        FieldDescriptor.Builder builder75 = FieldDescriptor.builder("onDeviceFaceMeshCreateLogEvent");
        zzbu zzbuVar75 = new zzbu();
        zzbuVar75.zza(74);
        zzax = builder75.withProperty(zzbuVar75.zzb()).build();
        FieldDescriptor.Builder builder76 = FieldDescriptor.builder("onDeviceFaceMeshLoadLogEvent");
        zzbu zzbuVar76 = new zzbu();
        zzbuVar76.zza(75);
        zzay = builder76.withProperty(zzbuVar76.zzb()).build();
        FieldDescriptor.Builder builder77 = FieldDescriptor.builder("onDeviceFaceMeshLogEvent");
        zzbu zzbuVar77 = new zzbu();
        zzbuVar77.zza(76);
        zzaz = builder77.withProperty(zzbuVar77.zzb()).build();
        FieldDescriptor.Builder builder78 = FieldDescriptor.builder("aggregatedOnDeviceFaceMeshLogEvent");
        zzbu zzbuVar78 = new zzbu();
        zzbuVar78.zza(77);
        zzaA = builder78.withProperty(zzbuVar78.zzb()).build();
        FieldDescriptor.Builder builder79 = FieldDescriptor.builder("smartReplyOptionalModuleLogEvent");
        zzbu zzbuVar79 = new zzbu();
        zzbuVar79.zza(78);
        zzaB = builder79.withProperty(zzbuVar79.zzb()).build();
        FieldDescriptor.Builder builder80 = FieldDescriptor.builder("textDetectionOptionalModuleLogEvent");
        zzbu zzbuVar80 = new zzbu();
        zzbuVar80.zza(80);
        zzaC = builder80.withProperty(zzbuVar80.zzb()).build();
        FieldDescriptor.Builder builder81 = FieldDescriptor.builder("onDeviceImageQualityAnalysisCreateLogEvent");
        zzbu zzbuVar81 = new zzbu();
        zzbuVar81.zza(81);
        zzaD = builder81.withProperty(zzbuVar81.zzb()).build();
        FieldDescriptor.Builder builder82 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLoadLogEvent");
        zzbu zzbuVar82 = new zzbu();
        zzbuVar82.zza(82);
        zzaE = builder82.withProperty(zzbuVar82.zzb()).build();
        FieldDescriptor.Builder builder83 = FieldDescriptor.builder("onDeviceImageQualityAnalysisLogEvent");
        zzbu zzbuVar83 = new zzbu();
        zzbuVar83.zza(83);
        zzaF = builder83.withProperty(zzbuVar83.zzb()).build();
        FieldDescriptor.Builder builder84 = FieldDescriptor.builder("aggregatedOnDeviceImageQualityAnalysisLogEvent");
        zzbu zzbuVar84 = new zzbu();
        zzbuVar84.zza(84);
        zzaG = builder84.withProperty(zzbuVar84.zzb()).build();
        FieldDescriptor.Builder builder85 = FieldDescriptor.builder("imageQualityAnalysisOptionalModuleLogEvent");
        zzbu zzbuVar85 = new zzbu();
        zzbuVar85.zza(88);
        zzaH = builder85.withProperty(zzbuVar85.zzb()).build();
        FieldDescriptor.Builder builder86 = FieldDescriptor.builder("imageCaptioningOptionalModuleLogEvent");
        zzbu zzbuVar86 = new zzbu();
        zzbuVar86.zza(89);
        zzaI = builder86.withProperty(zzbuVar86.zzb()).build();
        FieldDescriptor.Builder builder87 = FieldDescriptor.builder("onDeviceImageCaptioningCreateLogEvent");
        zzbu zzbuVar87 = new zzbu();
        zzbuVar87.zza(90);
        zzaJ = builder87.withProperty(zzbuVar87.zzb()).build();
        FieldDescriptor.Builder builder88 = FieldDescriptor.builder("onDeviceImageCaptioningLoadLogEvent");
        zzbu zzbuVar88 = new zzbu();
        zzbuVar88.zza(91);
        zzaK = builder88.withProperty(zzbuVar88.zzb()).build();
        FieldDescriptor.Builder builder89 = FieldDescriptor.builder("onDeviceImageCaptioningInferenceLogEvent");
        zzbu zzbuVar89 = new zzbu();
        zzbuVar89.zza(92);
        zzaL = builder89.withProperty(zzbuVar89.zzb()).build();
        FieldDescriptor.Builder builder90 = FieldDescriptor.builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent");
        zzbu zzbuVar90 = new zzbu();
        zzbuVar90.zza(93);
        zzaM = builder90.withProperty(zzbuVar90.zzb()).build();
        FieldDescriptor.Builder builder91 = FieldDescriptor.builder("onDeviceDocumentDetectionCreateLogEvent");
        zzbu zzbuVar91 = new zzbu();
        zzbuVar91.zza(94);
        zzaN = builder91.withProperty(zzbuVar91.zzb()).build();
        FieldDescriptor.Builder builder92 = FieldDescriptor.builder("onDeviceDocumentDetectionLoadLogEvent");
        zzbu zzbuVar92 = new zzbu();
        zzbuVar92.zza(95);
        zzaO = builder92.withProperty(zzbuVar92.zzb()).build();
        FieldDescriptor.Builder builder93 = FieldDescriptor.builder("onDeviceDocumentDetectionLogEvent");
        zzbu zzbuVar93 = new zzbu();
        zzbuVar93.zza(96);
        zzaP = builder93.withProperty(zzbuVar93.zzb()).build();
        FieldDescriptor.Builder builder94 = FieldDescriptor.builder("aggregatedOnDeviceDocumentDetectionLogEvent");
        zzbu zzbuVar94 = new zzbu();
        zzbuVar94.zza(97);
        zzaQ = builder94.withProperty(zzbuVar94.zzb()).build();
        FieldDescriptor.Builder builder95 = FieldDescriptor.builder("onDeviceDocumentCroppingCreateLogEvent");
        zzbu zzbuVar95 = new zzbu();
        zzbuVar95.zza(98);
        zzaR = builder95.withProperty(zzbuVar95.zzb()).build();
        FieldDescriptor.Builder builder96 = FieldDescriptor.builder("onDeviceDocumentCroppingLoadLogEvent");
        zzbu zzbuVar96 = new zzbu();
        zzbuVar96.zza(99);
        zzaS = builder96.withProperty(zzbuVar96.zzb()).build();
        FieldDescriptor.Builder builder97 = FieldDescriptor.builder("onDeviceDocumentCroppingLogEvent");
        zzbu zzbuVar97 = new zzbu();
        zzbuVar97.zza(100);
        zzaT = builder97.withProperty(zzbuVar97.zzb()).build();
        FieldDescriptor.Builder builder98 = FieldDescriptor.builder("aggregatedOnDeviceDocumentCroppingLogEvent");
        zzbu zzbuVar98 = new zzbu();
        zzbuVar98.zza(101);
        zzaU = builder98.withProperty(zzbuVar98.zzb()).build();
        FieldDescriptor.Builder builder99 = FieldDescriptor.builder("onDeviceDocumentEnhancementCreateLogEvent");
        zzbu zzbuVar99 = new zzbu();
        zzbuVar99.zza(102);
        zzaV = builder99.withProperty(zzbuVar99.zzb()).build();
        FieldDescriptor.Builder builder100 = FieldDescriptor.builder("onDeviceDocumentEnhancementLoadLogEvent");
        zzbu zzbuVar100 = new zzbu();
        zzbuVar100.zza(103);
        zzaW = builder100.withProperty(zzbuVar100.zzb()).build();
        FieldDescriptor.Builder builder101 = FieldDescriptor.builder("onDeviceDocumentEnhancementLogEvent");
        zzbu zzbuVar101 = new zzbu();
        zzbuVar101.zza(104);
        zzaX = builder101.withProperty(zzbuVar101.zzb()).build();
        FieldDescriptor.Builder builder102 = FieldDescriptor.builder("aggregatedOnDeviceDocumentEnhancementLogEvent");
        zzbu zzbuVar102 = new zzbu();
        zzbuVar102.zza(105);
        zzaY = builder102.withProperty(zzbuVar102.zzb()).build();
        FieldDescriptor.Builder builder103 = FieldDescriptor.builder("scannerAutoZoomEvent");
        zzbu zzbuVar103 = new zzbu();
        zzbuVar103.zza(106);
        zzaZ = builder103.withProperty(zzbuVar103.zzb()).build();
        FieldDescriptor.Builder builder104 = FieldDescriptor.builder("lowLightAutoExposureComputationEvent");
        zzbu zzbuVar104 = new zzbu();
        zzbuVar104.zza(107);
        zzba = builder104.withProperty(zzbuVar104.zzb()).build();
        FieldDescriptor.Builder builder105 = FieldDescriptor.builder("lowLightFrameProcessEvent");
        zzbu zzbuVar105 = new zzbu();
        zzbuVar105.zza(108);
        zzbb = builder105.withProperty(zzbuVar105.zzb()).build();
        FieldDescriptor.Builder builder106 = FieldDescriptor.builder("lowLightSceneDetectionEvent");
        zzbu zzbuVar106 = new zzbu();
        zzbuVar106.zza(109);
        zzbc = builder106.withProperty(zzbuVar106.zzb()).build();
        FieldDescriptor.Builder builder107 = FieldDescriptor.builder("onDeviceStainRemovalLogEvent");
        zzbu zzbuVar107 = new zzbu();
        zzbuVar107.zza(110);
        zzbd = builder107.withProperty(zzbuVar107.zzb()).build();
        FieldDescriptor.Builder builder108 = FieldDescriptor.builder("aggregatedOnDeviceStainRemovalLogEvent");
        zzbu zzbuVar108 = new zzbu();
        zzbuVar108.zza(RemoteKeyboard.SCAN_DELETE);
        zzbe = builder108.withProperty(zzbuVar108.zzb()).build();
        FieldDescriptor.Builder builder109 = FieldDescriptor.builder("stainRemovalOptionalModuleLogEvent");
        zzbu zzbuVar109 = new zzbu();
        zzbuVar109.zza(112);
        zzbf = builder109.withProperty(zzbuVar109.zzb()).build();
        FieldDescriptor.Builder builder110 = FieldDescriptor.builder("onDeviceShadowRemovalLogEvent");
        zzbu zzbuVar110 = new zzbu();
        zzbuVar110.zza(113);
        zzbg = builder110.withProperty(zzbuVar110.zzb()).build();
        FieldDescriptor.Builder builder111 = FieldDescriptor.builder("aggregatedOnDeviceShadowRemovalLogEvent");
        zzbu zzbuVar111 = new zzbu();
        zzbuVar111.zza(114);
        zzbh = builder111.withProperty(zzbuVar111.zzb()).build();
        FieldDescriptor.Builder builder112 = FieldDescriptor.builder("shadowRemovalOptionalModuleLogEvent");
        zzbu zzbuVar112 = new zzbu();
        zzbuVar112.zza(115);
        zzbi = builder112.withProperty(zzbuVar112.zzb()).build();
        FieldDescriptor.Builder builder113 = FieldDescriptor.builder("onDeviceDigitalInkSegmentationLogEvent");
        zzbu zzbuVar113 = new zzbu();
        zzbuVar113.zza(116);
        zzbj = builder113.withProperty(zzbuVar113.zzb()).build();
        FieldDescriptor.Builder builder114 = FieldDescriptor.builder("onDeviceDocumentScannerStartLogEvent");
        zzbu zzbuVar114 = new zzbu();
        zzbuVar114.zza(117);
        zzbk = builder114.withProperty(zzbuVar114.zzb()).build();
        FieldDescriptor.Builder builder115 = FieldDescriptor.builder("onDeviceDocumentScannerFinishLogEvent");
        zzbu zzbuVar115 = new zzbu();
        zzbuVar115.zza(118);
        zzbl = builder115.withProperty(zzbuVar115.zzb()).build();
        FieldDescriptor.Builder builder116 = FieldDescriptor.builder("onDeviceDocumentScannerUiStartLogEvent");
        zzbu zzbuVar116 = new zzbu();
        zzbuVar116.zza(119);
        zzbm = builder116.withProperty(zzbuVar116.zzb()).build();
        FieldDescriptor.Builder builder117 = FieldDescriptor.builder("onDeviceDocumentScannerUiFinishLogEvent");
        zzbu zzbuVar117 = new zzbu();
        zzbuVar117.zza(120);
        zzbn = builder117.withProperty(zzbuVar117.zzb()).build();
        FieldDescriptor.Builder builder118 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionStartLogEvent");
        zzbu zzbuVar118 = new zzbu();
        zzbuVar118.zza(121);
        zzbo = builder118.withProperty(zzbuVar118.zzb()).build();
        FieldDescriptor.Builder builder119 = FieldDescriptor.builder("documentScannerUiOptionalModuleSessionFinishLogEvent");
        zzbu zzbuVar119 = new zzbu();
        zzbuVar119.zza(122);
        zzbp = builder119.withProperty(zzbuVar119.zzb()).build();
        FieldDescriptor.Builder builder120 = FieldDescriptor.builder("onDeviceDocumentScannerUiCreateLogEvent");
        zzbu zzbuVar120 = new zzbu();
        zzbuVar120.zza(123);
        zzbq = builder120.withProperty(zzbuVar120.zzb()).build();
        FieldDescriptor.Builder builder121 = FieldDescriptor.builder("onDeviceSubjectSegmentationCreateLogEvent");
        zzbu zzbuVar121 = new zzbu();
        zzbuVar121.zza(124);
        zzbr = builder121.withProperty(zzbuVar121.zzb()).build();
        FieldDescriptor.Builder builder122 = FieldDescriptor.builder("onDeviceSubjectSegmentationLoadLogEvent");
        zzbu zzbuVar122 = new zzbu();
        zzbuVar122.zza(RemoteKeyboard.SCAN_LEFTSUPER);
        zzbs = builder122.withProperty(zzbuVar122.zzb()).build();
        FieldDescriptor.Builder builder123 = FieldDescriptor.builder("onDeviceSubjectSegmentationInferenceLogEvent");
        zzbu zzbuVar123 = new zzbu();
        zzbuVar123.zza(126);
        zzbt = builder123.withProperty(zzbuVar123.zzb()).build();
        FieldDescriptor.Builder builder124 = FieldDescriptor.builder("aggregatedOnDeviceSubjectSegmentationLogEvent");
        zzbu zzbuVar124 = new zzbu();
        zzbuVar124.zza(127);
        zzbu = builder124.withProperty(zzbuVar124.zzb()).build();
        FieldDescriptor.Builder builder125 = FieldDescriptor.builder("subjectSegmentationOptionalModuleLogEvent");
        zzbu zzbuVar125 = new zzbu();
        zzbuVar125.zza(128);
        zzbv = builder125.withProperty(zzbuVar125.zzb()).build();
        FieldDescriptor.Builder builder126 = FieldDescriptor.builder("documentScannerUiModuleScreenViewEvent");
        zzbu zzbuVar126 = new zzbu();
        zzbuVar126.zza(129);
        zzbw = builder126.withProperty(zzbuVar126.zzb()).build();
        FieldDescriptor.Builder builder127 = FieldDescriptor.builder("documentScannerUiModuleScreenClickEvent");
        zzbu zzbuVar127 = new zzbu();
        zzbuVar127.zza(130);
        zzbx = builder127.withProperty(zzbuVar127.zzb()).build();
        FieldDescriptor.Builder builder128 = FieldDescriptor.builder("documentScannerUiModuleScreenErrorEvent");
        zzbu zzbuVar128 = new zzbu();
        zzbuVar128.zza(TarConstants.PREFIXLEN_XSTAR);
        zzby = builder128.withProperty(zzbuVar128.zzb()).build();
    }

    private zziu() {
    }

    @Override // com.google.firebase.encoders.Encoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, ObjectEncoderContext objectEncoderContext) throws IOException {
        zzpe zzpeVar = (zzpe) obj;
        ObjectEncoderContext objectEncoderContext2 = objectEncoderContext;
        objectEncoderContext2.add(zzb, zzpeVar.zzh());
        objectEncoderContext2.add(zzc, zzpeVar.zzc());
        objectEncoderContext2.add(zzd, (Object) null);
        objectEncoderContext2.add(zze, zzpeVar.zzb());
        objectEncoderContext2.add(zzf, (Object) null);
        objectEncoderContext2.add(zzg, (Object) null);
        objectEncoderContext2.add(zzh, (Object) null);
        objectEncoderContext2.add(zzi, (Object) null);
        objectEncoderContext2.add(zzj, (Object) null);
        objectEncoderContext2.add(zzk, (Object) null);
        objectEncoderContext2.add(zzl, (Object) null);
        objectEncoderContext2.add(zzm, (Object) null);
        objectEncoderContext2.add(zzn, (Object) null);
        objectEncoderContext2.add(zzo, (Object) null);
        objectEncoderContext2.add(zzp, (Object) null);
        objectEncoderContext2.add(zzq, (Object) null);
        objectEncoderContext2.add(zzr, (Object) null);
        objectEncoderContext2.add(zzs, zzpeVar.zzd());
        objectEncoderContext2.add(zzt, zzpeVar.zzf());
        objectEncoderContext2.add(zzu, zzpeVar.zze());
        objectEncoderContext2.add(zzv, (Object) null);
        objectEncoderContext2.add(zzw, (Object) null);
        objectEncoderContext2.add(zzx, (Object) null);
        objectEncoderContext2.add(zzy, (Object) null);
        objectEncoderContext2.add(zzz, (Object) null);
        objectEncoderContext2.add(zzA, (Object) null);
        objectEncoderContext2.add(zzB, (Object) null);
        objectEncoderContext2.add(zzC, (Object) null);
        objectEncoderContext2.add(zzD, (Object) null);
        objectEncoderContext2.add(zzE, (Object) null);
        objectEncoderContext2.add(zzF, (Object) null);
        objectEncoderContext2.add(zzG, (Object) null);
        objectEncoderContext2.add(zzH, (Object) null);
        objectEncoderContext2.add(zzI, (Object) null);
        objectEncoderContext2.add(zzJ, (Object) null);
        objectEncoderContext2.add(zzK, (Object) null);
        objectEncoderContext2.add(zzL, (Object) null);
        objectEncoderContext2.add(zzM, (Object) null);
        objectEncoderContext2.add(zzN, (Object) null);
        objectEncoderContext2.add(zzO, (Object) null);
        objectEncoderContext2.add(zzP, (Object) null);
        objectEncoderContext2.add(zzQ, (Object) null);
        objectEncoderContext2.add(zzR, (Object) null);
        objectEncoderContext2.add(zzS, (Object) null);
        objectEncoderContext2.add(zzT, (Object) null);
        objectEncoderContext2.add(zzU, zzpeVar.zza());
        objectEncoderContext2.add(zzV, (Object) null);
        objectEncoderContext2.add(zzW, (Object) null);
        objectEncoderContext2.add(zzX, (Object) null);
        objectEncoderContext2.add(zzY, (Object) null);
        objectEncoderContext2.add(zzZ, zzpeVar.zzg());
        objectEncoderContext2.add(zzaa, (Object) null);
        objectEncoderContext2.add(zzab, (Object) null);
        objectEncoderContext2.add(zzac, (Object) null);
        objectEncoderContext2.add(zzad, (Object) null);
        objectEncoderContext2.add(zzae, (Object) null);
        objectEncoderContext2.add(zzaf, (Object) null);
        objectEncoderContext2.add(zzag, (Object) null);
        objectEncoderContext2.add(zzah, (Object) null);
        objectEncoderContext2.add(zzai, (Object) null);
        objectEncoderContext2.add(zzaj, (Object) null);
        objectEncoderContext2.add(zzak, (Object) null);
        objectEncoderContext2.add(zzal, (Object) null);
        objectEncoderContext2.add(zzam, (Object) null);
        objectEncoderContext2.add(zzan, (Object) null);
        objectEncoderContext2.add(zzao, (Object) null);
        objectEncoderContext2.add(zzap, (Object) null);
        objectEncoderContext2.add(zzaq, (Object) null);
        objectEncoderContext2.add(zzar, (Object) null);
        objectEncoderContext2.add(zzas, (Object) null);
        objectEncoderContext2.add(zzat, (Object) null);
        objectEncoderContext2.add(zzau, (Object) null);
        objectEncoderContext2.add(zzav, (Object) null);
        objectEncoderContext2.add(zzaw, (Object) null);
        objectEncoderContext2.add(zzax, (Object) null);
        objectEncoderContext2.add(zzay, (Object) null);
        objectEncoderContext2.add(zzaz, (Object) null);
        objectEncoderContext2.add(zzaA, (Object) null);
        objectEncoderContext2.add(zzaB, (Object) null);
        objectEncoderContext2.add(zzaC, (Object) null);
        objectEncoderContext2.add(zzaD, (Object) null);
        objectEncoderContext2.add(zzaE, (Object) null);
        objectEncoderContext2.add(zzaF, (Object) null);
        objectEncoderContext2.add(zzaG, (Object) null);
        objectEncoderContext2.add(zzaH, (Object) null);
        objectEncoderContext2.add(zzaI, (Object) null);
        objectEncoderContext2.add(zzaJ, (Object) null);
        objectEncoderContext2.add(zzaK, (Object) null);
        objectEncoderContext2.add(zzaL, (Object) null);
        objectEncoderContext2.add(zzaM, (Object) null);
        objectEncoderContext2.add(zzaN, (Object) null);
        objectEncoderContext2.add(zzaO, (Object) null);
        objectEncoderContext2.add(zzaP, (Object) null);
        objectEncoderContext2.add(zzaQ, (Object) null);
        objectEncoderContext2.add(zzaR, (Object) null);
        objectEncoderContext2.add(zzaS, (Object) null);
        objectEncoderContext2.add(zzaT, (Object) null);
        objectEncoderContext2.add(zzaU, (Object) null);
        objectEncoderContext2.add(zzaV, (Object) null);
        objectEncoderContext2.add(zzaW, (Object) null);
        objectEncoderContext2.add(zzaX, (Object) null);
        objectEncoderContext2.add(zzaY, (Object) null);
        objectEncoderContext2.add(zzaZ, (Object) null);
        objectEncoderContext2.add(zzba, (Object) null);
        objectEncoderContext2.add(zzbb, (Object) null);
        objectEncoderContext2.add(zzbc, (Object) null);
        objectEncoderContext2.add(zzbd, (Object) null);
        objectEncoderContext2.add(zzbe, (Object) null);
        objectEncoderContext2.add(zzbf, (Object) null);
        objectEncoderContext2.add(zzbg, (Object) null);
        objectEncoderContext2.add(zzbh, (Object) null);
        objectEncoderContext2.add(zzbi, (Object) null);
        objectEncoderContext2.add(zzbj, (Object) null);
        objectEncoderContext2.add(zzbk, (Object) null);
        objectEncoderContext2.add(zzbl, (Object) null);
        objectEncoderContext2.add(zzbm, (Object) null);
        objectEncoderContext2.add(zzbn, (Object) null);
        objectEncoderContext2.add(zzbo, (Object) null);
        objectEncoderContext2.add(zzbp, (Object) null);
        objectEncoderContext2.add(zzbq, (Object) null);
        objectEncoderContext2.add(zzbr, (Object) null);
        objectEncoderContext2.add(zzbs, (Object) null);
        objectEncoderContext2.add(zzbt, (Object) null);
        objectEncoderContext2.add(zzbu, (Object) null);
        objectEncoderContext2.add(zzbv, (Object) null);
        objectEncoderContext2.add(zzbw, (Object) null);
        objectEncoderContext2.add(zzbx, (Object) null);
        objectEncoderContext2.add(zzby, (Object) null);
    }
}
